import type { ParsedJobDraft } from './aiTypes'
const cities=['Delhi','Gurugram','Gurgaon','Noida','Pune','Bengaluru','Bangalore','Hyderabad','Mumbai','Chennai','Kolkata','Ahmedabad']
const titleRules:[RegExp,string,string][]=[[/data\s+engineer/i,'Data Engineer','data-engineering'],[/data\s+analyst/i,'Data Analyst','data-analytics'],[/data\s+scientist/i,'Data Scientist','data-science'],[/front[ -]?end/i,'Frontend Developer','frontend-development'],[/back[ -]?end/i,'Backend Developer','backend-development'],[/full[ -]?stack/i,'Full Stack Developer','full-stack-development'],[/devops/i,'DevOps Engineer','devops'],[/cyber ?security/i,'Cybersecurity Engineer','cybersecurity'],[/business analyst/i,'Business Analyst','business-analysis'],[/machine learning|\bai\b|\bml\b/i,'AI / ML Engineer','ai-ml']]
const knownSkills=['Snowflake','Python','dbt','SQL','ETL','ELT','React','Node.js','TypeScript','Java','AWS','Azure','GCP','Databricks','Spark','Power BI','Tableau','Docker','Kubernetes','Terraform']
function unique(xs:string[]){return [...new Set(xs.map(x=>x.trim()).filter(Boolean))]}
function extractLabeled(text:string,label:RegExp){const m=text.match(new RegExp(`${label.source}\\s*:?\\s*([^\\n.]+)`,'i'));return m?.[1]??''}
export function parseJobFallback(rawText:string):ParsedJobDraft{
 const text=rawText.trim();const titleRule=titleRules.find(([r])=>r.test(text));const exp=text.match(/(\d+(?:\.\d+)?)\s*(?:-|–|to)\s*(\d+(?:\.\d+)?)\s*(?:years?|yrs?)/i)||text.match(/(\d+(?:\.\d+)?)\+\s*(?:years?|yrs?)/i);const duration=text.match(/(\d+)\s*(months?|mos?)/i)||text.match(/(\d+)\s*(years?|yrs?)\s*(?:contract|project)?/i);const months=duration?Number(duration[1])*(/year|yr/i.test(duration[2])?12:1):null;const mode=/hybrid/i.test(text)?'hybrid':/remote|work from home|wfh/i.test(text)?'remote':/on[- ]?site|office/i.test(text)?'onsite':'onsite';
 const mandatorySection=extractLabeled(text,/mandatory|required|must[- ]?have/);const preferredSection=extractLabeled(text,/preferred|good[- ]?to[- ]?have|nice[- ]?to[- ]?have/);const mandatory=knownSkills.filter(s=>mandatorySection.toLowerCase().includes(s.toLowerCase()));const preferred=knownSkills.filter(s=>preferredSection.toLowerCase().includes(s.toLowerCase())||new RegExp(`${s.replace('.','\\.')}\\s+(?:good|nice) to have`,'i').test(text));const all=knownSkills.filter(s=>text.toLowerCase().includes(s.toLowerCase()));const finalMandatory=mandatory.length?mandatory:all.filter(s=>!preferred.includes(s)).slice(0,10);const locations=unique(cities.filter(c=>new RegExp(`\\b${c}\\b`,'i').test(text)).map(c=>c==='Gurgaon'?'Gurugram':c==='Bangalore'?'Bengaluru':c));const emp=/intern/i.test(text)?'internship':/freelance/i.test(text)?'freelance':/part[- ]?time/i.test(text)?'part_time':/permanent|full[- ]?time/i.test(text)?'permanent':'contract';const title=titleRule?.[1]??(text.split(/[\n.]/)[0].replace(/^(urgent|opening for|hiring)\s*/i,'').trim().slice(0,160)||'Job Opening');const summary=[title,exp?`${exp[1]}${exp[2]?`-${exp[2]}`:'+'} years`:null,mode].filter(Boolean).join(' · ');
 return {title,categorySlug:titleRule?.[2]??null,companyName:null,clientName:null,durationText:duration?duration[0]:null,durationMonths:months,experienceMinYears:exp?Number(exp[1]):null,experienceMaxYears:exp&&exp[2]?Number(exp[2]):exp?Number(exp[1]):null,employmentType:emp,workMode:mode,locations,mandatorySkills:unique(finalMandatory),preferredSkills:unique(preferred),salaryText:null,description:text,keywords:unique([...all,titleRule?.[2]??'']).slice(0,20),shortSummary:summary.slice(0,320),fieldConfidence:{title:titleRule?0.9:0.4,experience:exp?0.9:0,duration:duration?0.9:0,workMode:/hybrid|remote|onsite|office/i.test(text)?0.85:0.3,skills:all.length?0.75:0,location:locations.length?0.8:0},fallbackUsed:true,sourceText:text}
}
