import{useEffect,useMemo,useState}from'react';import{useNavigate,useParams}from'react-router-dom';import{JobForm}from'./JobForm';import{getJobForEdit,updateDraft}from'./jobsApi';import{recordToDraft,validateJobForPublish,type PublishField}from'./jobMappers';import{publishJob,submitForReview}from'./jobActions';import type{JobRecord}from'./jobTypes'

function friendlyPublishError(error:unknown){const message=error instanceof Error?error.message:'Unable to publish job';if(message.toLowerCase().includes('job is incomplete for publishing'))return 'Complete the required fields before publishing';return message}

export function JobEditorPage(){const{id}=useParams();const nav=useNavigate();const[job,setJob]=useState<JobRecord|null>(null);const[message,setMessage]=useState('');const[isError,setIsError]=useState(false);const[publishIssues,setPublishIssues]=useState<Array<{field:PublishField;message:string}>>([]);const[publishing,setPublishing]=useState(false);useEffect(()=>{if(id)void getJobForEdit(id).then(setJob)},[id]);const publishErrors=useMemo(()=>Object.fromEntries(publishIssues.map(i=>[i.field,i.message])) as Partial<Record<PublishField,string>>,[publishIssues]);if(!job)return <div className="page"><div className="loading">Loading job…</div></div>;

async function handlePublish(){const issues=validateJobForPublish(job!);if(issues.length){setPublishIssues(issues);setMessage(issues[0].message);setIsError(true);return}setPublishIssues([]);setPublishing(true);setMessage('');try{await publishJob(job!.id);setIsError(false);setMessage('Job published');nav('/admin/jobs')}catch(e){setIsError(true);setMessage(friendlyPublishError(e))}finally{setPublishing(false)}}

return <div className="page"><div className="page-header"><div><p className="eyebrow">Job workspace</p><h1>Edit job</h1><p className="muted">Current status: <strong>{job.status.replace('_',' ')}</strong></p></div><div className="actions">{job.status==='draft'&&<button className="btn secondary" onClick={()=>void submitForReview(job.id).then(()=>{setIsError(false);setMessage('Submitted for review')}).catch(e=>{setIsError(true);setMessage(e instanceof Error?e.message:'Unable to submit for review')})}>Submit for review</button>}<button className="btn primary" disabled={publishing} onClick={()=>void handlePublish()}>{publishing?'Publishing…':'Publish'}</button></div></div>{message&&<div className={`alert ${isError?'error':''}`}>{message}</div>}<section className="panel"><JobForm initial={recordToDraft(job)} publishErrors={publishErrors} onSave={async(v)=>{const updated=await updateDraft(job.id,v);setJob(updated);setPublishIssues([]);setIsError(false);setMessage('Draft saved')}}/></section></div>}
